# Machine Learning - Fall 2021
## Final Challenge Assignment

### Data preprocessing

In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

In [2]:
X_train = pd.read_csv("Data\data_cleaned_train_comments_X.csv")
X_train

host_since  host_response_rate  host_is_superhost  \
0        0.268086                 1.0                1.0   
1        0.333333                 0.8                0.0   
2        0.178542                 0.0                0.0   
3        0.283374                 0.9                0.0   
4        0.763309                 1.0                1.0   
...           ...                 ...                ...   
29980    0.300846                 1.0                1.0   
29981    0.453999                 1.0                0.0   
29982    0.547639                 0.0                0.0   
29983    0.387387                 0.0                0.0   
29984    0.307671                 1.0                0.0   

       host_total_listings_count  host_has_profile_pic  \
0                       0.001129                   1.0   
1                       0.001129                   1.0   
2                       0.002257                   1.0   
3                       0.001129                   1.0   
4                       0.013544                   1.0   
...                          ...                   ...   
29980                   0.001129                   1.0   
29981                   0.001129                   1.0   
29982                   0.001129                   1.0   
29983                   0.001129                   1.0   
29984                   0.001129                   1.0   

       host_identity_verified  latitude  longitude  accommodates  bathrooms  \
0                         1.0  0.577131   0.460826      0.066667   0.064516   
1                         1.0  0.579074   0.447318      0.066667   0.064516   
2                         1.0  0.534726   0.467852      0.066667   0.064516   
3                         0.0  0.320020   0.519025      0.200000   0.064516   
4                         0.0  0.416274   0.507569      0.200000   0.258065   
...                       ...       ...        ...           ...        ...   
29980                     1.0  0.787555   0.554719      0.066667   0.064516   
29981                     1.0  0.659987   0.536712      0.066667   0.064516   
29982                     1.0  0.506841   0.471084      0.066667   0.064516   
29983                     1.0  0.623418   0.526313      0.066667   0.064516   
29984                     1.0  0.594372   0.491372      0.466667   0.161290   

       ...  Whitestone.1  Williamsbridge  Williamsburg.1  Willowbrook  \
0      ...           0.0             0.0             0.0          0.0   
1      ...           0.0             0.0             0.0          0.0   
2      ...           0.0             0.0             0.0          0.0   
3      ...           0.0             0.0             0.0          0.0   
4      ...           0.0             0.0             0.0          0.0   
...    ...           ...             ...             ...          ...   
29980  ...           0.0             0.0             0.0          0.0   
29981  ...           0.0             0.0             0.0          0.0   
29982  ...           0.0             0.0             0.0          0.0   
29983  ...           0.0             0.0             0.0          0.0   
29984  ...           0.0             0.0             0.0          0.0   

       Windsor Terrace  Woodhaven.1  Woodlawn  Woodrow  Woodside.1  comments  
0                  0.0          0.0       0.0      0.0         0.0  0.741085  
1                  0.0          0.0       0.0      0.0         0.0  0.652068  
2                  0.0          0.0       0.0      0.0         0.0  0.500000  
3                  0.0          0.0       0.0      0.0         0.0  0.735782  
4                  0.0          0.0       0.0      0.0         0.0  0.500000  
...                ...          ...       ...      ...         ...       ...  
29980              0.0          0.0       0.0      0.0         0.0  0.610914  
29981              0.0          0.0       0.0      0.0         0.0  0.500000  
29982              0.0          0.0       0.0      0

In [3]:
y_train = pd.read_csv("Data\data_cleaned_train_y.csv")
y_train

price
0      4.564348
1      4.828314
2      4.787492
3      4.828314
4      5.521461
...         ...
29980  4.605170
29981  4.882802
29982  4.828314
29983  4.553877
29984  6.551080

[29985 rows x 1 columns]

In [4]:
X_val = pd.read_csv("Data\data_cleaned_val_comments_X.csv")
X_val

host_since  host_response_rate  host_is_superhost  \
0       0.117383                1.00                0.0   
1       0.606436                0.00                0.0   
2       0.554471                0.00                0.0   
3       0.319441                0.00                0.0   
4       0.613822                1.00                0.0   
...          ...                 ...                ...   
9991    0.273806                0.00                0.0   
9992    0.414403                1.00                0.0   
9993    0.167766                1.00                0.0   
9994    0.223160                0.90                0.0   
9995    0.455289                0.92                0.0   

      host_total_listings_count  host_has_profile_pic  host_identity_verified  \
0                      0.001129                   1.0                     0.0   
1                      0.001129                   1.0                     1.0   
2                      0.001129                   1.0                     1.0   
3                      0.001129                   1.0                     1.0   
4                      0.001129                   1.0                     1.0   
...                         ...                   ...                     ...   
9991                   0.002257                   1.0                     1.0   
9992                   0.009029                   1.0                     1.0   
9993                   0.010158                   1.0                     1.0   
9994                   0.001129                   1.0                     0.0   
9995                   0.004515                   1.0                     0.0   

      latitude  longitude  accommodates  bathrooms  ...  Whitestone.1  \
0     0.661276   0.474752      0.400000   0.020833  ...           0.0   
1     0.416019   0.487202      0.066667   0.020833  ...           0.0   
2     0.712850   0.516382      0.266667   0.031250  ...           0.0   
3     0.698307   0.502197      0.133333   0.020833  ...           0.0   
4     0.400084   0.529808      0.066667   0.020833  ...           0.0   
...        ...        ...           ...        ...  ...           ...   
9991  0.543038   0.525648      0.200000   0.020833  ...           0.0   
9992  0.733105   0.585357      0.600000   0.041667  ...           0.0   
9993  0.704948   0.489309      0.133333   0.020833  ...           0.0   
9994  0.544340   0.488787      0.066667   0.020833  ...           0.0   
9995  0.826906   0.564289      0.066667   0.020833  ...           0.0   

      Williamsbridge  Williamsburg.1  Willowbrook  Windsor Terrace  \
0                0.0             0.0          0.0              0.0   
1                0.0             0.0          0.0              0.0   
2                0.0             0.0          0.0              0.0   
3                0.0             0.0          0.0              0.0   
4                0.0             0.0          0.0              0.0   
...              ...             ...          ...              ...   
9991             0.0             1.0          0.0              0.0   
9992             0.0             0.0          0.0              0.0   
9993             0.0             0.0          0.0              0.0   
9994             0.0             0.0          0.0              0.0   
9995             0.0             0.0          0.0              0.0   

      Woodhaven.1  Woodlawn  Woodrow  Woodside.1  comments  
0             0.0       0.0      0.0         0.0  0.584925  
1             0.0       0.0      0.0         0.0  0.685401  
2             0.0       0.0      0.0         0.0  0.411765  
3             0.0       0.0      0.0         0.0  0.615196  
4             0.0       0.0      0.0         0.0  0.681281  
...           ...       ...      ...         ...       ...  
9991          0.0       0.0      0.0         0.0  0.411765  
9992          0.0       0.0      0.0         0.0  0.615967  
9993          0.0       0.0      0.0         0.0  0.41176

In [5]:
y_val = pd.read_csv("Data\data_cleaned_val_y.csv")
y_val

price
0     5.129899
1     5.010635
2     5.783825
3     5.192957
4     4.248495
...        ...
9991  4.442651
9992  5.634790
9993  4.905275
9994  5.192957
9995  4.234107

[9996 rows x 1 columns]

### Implement the simple Linear Model

In [6]:
X_train_full = X_train.to_numpy()
y_train_full = y_train.to_numpy()
features_to_drop = set()

In [7]:
def correlated_features(X, threshold=0.8):
    correlated_features = set() # set of indices of features
    corr_matrix = np.corrcoef(X.T) # calculate the correlation matrix
    for i in range(len(corr_matrix[0])):
        for j in range(i):
            if np.abs(corr_matrix[i][j]) > threshold:
                correlated_features.add(i)
    return correlated_features

In [8]:
def constant_features(X):
    const_features = set()
    for i in range(X.shape[1]):
        if np.std(X[:, i], axis=0) == 0:
            const_features.add(i)
    return const_features

In [9]:
def duplicate_features(X):
    dup_features = set()
    for i in range(X.shape[1]):
        for j in range(i+1, X.shape[1]):
            if np.array_equal(X[:,i], X[:,j]):
                dup_features.add(j)
    return dup_features

In [10]:
features_to_drop = set()
corr_features = correlated_features(X_train_full)
const_features = constant_features(X_train_full)
dup_features = duplicate_features(X_train_full)
features_to_drop.update(const_features)
features_to_drop.update(dup_features)

D:\Study\Utilities\anaconda3\lib\site-packages\numpy\lib\function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
D:\Study\Utilities\anaconda3\lib\site-packages\numpy\lib\function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]


In [11]:
def preprocess(X, y):
    X = np.delete(X, list(features_to_drop), axis=1)
    return X, y

In [12]:
X_train_processed, y_train_full = preprocess(X_train_full, y_train_full)
X_train_processed.shape

(29985, 676)

In [13]:
X_val_full = X_val.to_numpy()
y_val_full = y_val.to_numpy()

In [14]:
X_val_processed, y_val_full = preprocess(X_val_full, y_val_full)
X_val_processed.shape

(9996, 676)

#### Linear Regression using Gradient Descent and L2-Regularisation

In [15]:
import time

def add_column(X):
    X = np.vstack((np.ones((X.shape[0],)), X.T)).T
    return X

def reg_predict(X_train, theta):
    return np.dot(X_train, theta)

def loss_gradient(X_train, y_train, theta):
    loss_grad = ((reg_predict(X_train, theta)-y_train) * X_train).mean(axis=0)[:, np.newaxis]
    return loss_grad

def loss_gradient_with_reg(X_train, y_train, theta, lambda_=0.0):
    unreg_grad = loss_gradient(X_train, y_train, theta)
    
    reg_term = (lambda_/X_train.shape[0])*theta
    
    reg_term = reg_term.reshape(-1, 1)
    unreg_grad = unreg_grad.reshape(-1, 1)
    reg_term[0] = 0
    
    return unreg_grad + reg_term

def fit(loss_gradient_with_reg, X_train, y_train, theta_init, n_iter = 2000, alpha=0.01):
    theta_current = theta_init.copy()
    for i in range(n_iter):
        theta_current = theta_current - alpha*loss_gradient_with_reg(X_train, y_train, theta_current, 1.0)
    return theta_current

def train(X_train, y_train):
    time_start = time.time()
    
    X_train= add_column(X_train)
    theta_init = np.zeros((X_train.shape[1], 1))
    theta_current = fit(loss_gradient_with_reg, X_train, y_train, theta_init)

    time_end = time.time()
    print(f"{np.round((time_end - time_start) /60, 2)} minutes")
    
    return theta_current

def predict(X_val, theta):
    X_val = add_column(X_val)
    return np.dot(X_val, theta)

Train and predict on full data.

In [16]:
# Importing metrics libraries for evalutation.

from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [17]:
theta_current = train(X_train_full, y_train_full)

2.0 minutes


In [18]:
theta_current.flatten()

array([ 6.38122367e-01,  1.35670869e-01,  4.35540848e-02,  1.77104330e-02,
       -1.56592432e-03,  5.96664818e-01, -5.36476763e-02,  2.41707133e-01,
        2.48183769e-01,  3.98184093e-01,  9.66217707e-02,  1.75573218e-01,
        7.96702014e-02,  3.47856066e-02,  4.07854179e-02,  1.32161652e-01,
       -2.27047617e-02, -3.54105586e-03,  5.64365005e-04,  0.00000000e+00,
       -2.76718556e-02, -2.14442508e-02, -3.92589934e-02, -6.14569235e-03,
       -3.81749728e-02, -3.75979047e-02,  1.35303810e-02, -4.80352639e-02,
        2.67128341e-02,  0.00000000e+00, -1.98138931e-03,  7.87655228e-04,
       -1.94319096e-02,  7.57001045e-03, -2.73034924e-03, -6.65933897e-03,
        1.19754740e-03, -4.63341002e-03,  2.30630660e-04,  2.35926491e-01,
        5.71581684e-05,  1.25895358e-03, -2.21620189e-03, -2.00360775e-03,
       -3.03565011e-03, -5.45855518e-03,  1.78187718e-03,  5.45121660e-01,
       -2.21620189e-03,  1.03139369e-02,  4.98959621e-03,  3.98500606e-03,
       -2.75707468e-02, -

In [19]:
y_pred = predict(X_val_full, theta_current)

In [20]:
mse = mean_squared_error(y_val_full, y_pred)
print(mse)

0.21531120044106114


Train and predict on processed data.

In [21]:
theta_current = train(X_train_processed, y_train_full)

1.75 minutes


In [22]:
theta_current.flatten()

array([ 6.38121444e-01,  1.35675351e-01,  4.35537284e-02,  1.77144410e-02,
       -1.56829159e-03,  5.96664757e-01, -5.36525001e-02,  2.41706544e-01,
        2.48180032e-01,  3.98190739e-01,  9.66221152e-02,  1.75574033e-01,
        7.96709695e-02,  3.47831972e-02,  4.07884792e-02,  1.32162829e-01,
       -2.26995641e-02, -3.54124757e-03,  5.64360132e-04, -2.76732727e-02,
       -2.14425012e-02, -3.92588451e-02, -6.14552636e-03, -3.81739947e-02,
       -3.75968814e-02,  1.35298505e-02, -4.80351469e-02,  2.67129754e-02,
       -1.98041590e-03,  7.90883933e-04, -1.94337112e-02,  7.58409206e-03,
       -2.72294452e-03, -6.65559424e-03,  1.19806402e-03, -4.63782799e-03,
        2.31125662e-04,  2.35929092e-01,  5.73109542e-05,  1.25954518e-03,
       -2.22465852e-03, -2.00551022e-03, -3.04197538e-03, -5.45348401e-03,
        1.77587015e-03,  5.45120582e-01,  1.03151443e-02,  4.97591646e-03,
        3.98651840e-03, -2.75743014e-02, -3.60762064e-03, -1.75705648e-02,
       -2.60466892e-02, -

In [23]:
y_pred = predict(X_val_processed, theta_current)

In [24]:
mse = mean_squared_error(y_val_full, y_pred)
print(mse)

0.21531073391617075


#### Normal Equation with L2-Regularisation

In [25]:
from numpy.linalg import inv

def search_lambda(X_train_full, y_train_full):
    time_start = time.time()
    
    curr_lambda = 1.0
    final_lambda = 1.0
    min_mse = float('inf')
    avg_curr_mse = 0.0
    
    for i in range(100):
        mse_runs = []
        for i in range(5): # 5-fold cross-validation
            rows = X_train_full.shape[0]
            random_indices = np.random.choice(rows, size=round(0.8*X_train_full.shape[0]), replace=False)
            X_train_curr = np.delete(X_train_full, random_indices, axis=0)
            X_val_curr = X_train_full[random_indices, :]
            y_train_curr = np.delete(y_train_full, random_indices, axis=0)
            y_val_curr = y_train_full[random_indices, :]

            current_theta = train_normal(X_train_curr, y_train_curr, curr_lambda)
            y_pred_curr = predict(X_val_curr, current_theta)
            current_mse = np.square(np.subtract(y_val_curr, y_pred_curr)).mean()
            mse_runs.append(current_mse)
        
        avg_curr_mse = np.mean(mse_runs)
        
        if avg_curr_mse < min_mse:
            min_mse = avg_curr_mse
            final_lambda = curr_lambda
        curr_lambda += 0.1
        
    time_end = time.time()
    print(f"{np.round((time_end - time_start) /60, 2)} minutes")
    
    return min_mse, final_lambda

def train_normal(X_train, y_train, lambda_=0.0):

    lambda_matrix = lambda_ * np.identity(X_train.shape[1])
    lambda_matrix = np.insert(lambda_matrix, 0, 0, axis=0)
    lambda_matrix = np.insert(lambda_matrix, 0, 0, axis=1)
    X_train= add_column(X_train)
    theta = inv(X_train.T @ X_train + lambda_matrix) @ (X_train.T @ y_train)
    
    return theta

def predict(X_val, theta):
    X_val = add_column(X_val)
    return np.dot(X_val, theta)

Train and predict on full data.

In [26]:
min_mse_train, lambda_ = search_lambda(X_train_full, y_train_full)
lambda_

2.33 minutes


4.400000000000001

In [27]:
theta_final = train_normal(X_train_full, y_train_full, lambda_)

In [28]:
theta_final.flatten()

array([ 5.19400231e+00,  8.93693512e-02, -7.94129634e-02,  5.82558036e-02,
       -3.91345025e-02, -1.72513421e-01, -2.18104088e-03, -6.45102614e-02,
       -1.10075654e+00,  1.38981168e+00,  8.77285642e-01,  1.30222985e+00,
       -5.43519945e-01,  8.58863578e-03,  8.50179688e-03,  5.27743578e-01,
       -5.09710023e-02, -1.04166843e+00,  1.19561317e-01,  0.00000000e+00,
       -1.15377540e-01,  1.39737766e-01, -9.32679790e-02,  2.89787862e-01,
       -8.94958525e-02, -1.11681474e-01,  4.39016918e-02, -2.67565629e-01,
       -2.19395914e-05,  0.00000000e+00,  2.43914302e-03,  1.69938718e-02,
       -3.10242150e-01,  6.38504097e-03,  1.11556108e-02, -7.10960479e-03,
       -6.18065531e-02, -1.58995154e-01,  3.97507040e-04, -2.21726848e-02,
        5.65758636e-02,  3.02174139e-03, -8.10129988e-02, -1.66123936e-02,
       -1.86574543e-02, -1.15091690e-02,  1.11811103e-02, -1.90367319e-02,
       -8.10129988e-02,  2.84183501e-02,  6.35408466e-02,  1.31566910e-03,
       -6.33176436e-02, -

In [29]:
y_pred_norm = predict(X_val_full, theta_final)

In [30]:
mse = mean_squared_error(y_val_full, y_pred_norm)
print(mse)

0.15423986314049704


In [31]:
r2 = r2_score(y_val_full, y_pred_norm)
print(r2)

0.6783927416114865


Train and predict on processed data.

In [32]:
min_mse_train, lambda_ = search_lambda(X_train_processed, y_train_full)
lambda_

1.96 minutes


4.8999999999999995

In [33]:
theta_final = train_normal(X_train_processed, y_train_full, lambda_)

In [34]:
theta_final.flatten()

array([ 5.16280005e+00,  8.94857252e-02, -7.83448400e-02,  5.81921179e-02,
       -4.00206053e-02, -1.71456278e-01, -2.24105284e-03, -6.19994512e-02,
       -1.04852215e+00,  1.38682411e+00,  8.60532682e-01,  1.28816856e+00,
       -5.04385628e-01,  8.57673219e-03,  8.58338177e-03,  5.27045280e-01,
       -5.10118878e-02, -9.98065063e-01,  1.11099335e-01, -1.15387958e-01,
        1.38864354e-01, -9.29014963e-02,  2.88556140e-01, -8.99045192e-02,
       -1.11832272e-01,  4.47359271e-02, -2.66144192e-01, -8.03480778e-05,
        2.57192510e-03,  1.69287587e-02, -3.08204904e-01,  6.42441809e-03,
        1.11481721e-02, -7.08060309e-03, -5.92445169e-02, -1.59809671e-01,
        4.05389087e-04, -2.21485274e-02,  5.16628084e-02,  3.07738786e-03,
       -1.26303902e-01, -1.65576518e-02, -1.84980347e-02, -1.15731222e-02,
        1.09125205e-02, -1.93488085e-02,  2.83080584e-02,  6.23907789e-02,
        1.34257389e-03, -6.33445801e-02, -2.70286627e-02, -3.80826281e-03,
       -3.53559074e-02, -

In [35]:
y_pred_norm = predict(X_val_processed, theta_final)

In [36]:
mse = mean_squared_error(y_val_full, y_pred_norm)
print(mse)

0.15413717289759224


In [37]:
r2 = r2_score(y_val_full, y_pred_norm)
print(r2)

0.6786068621819501
